# ~/.config/alacritty/alacritty.toml

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "full"
startup_mode = "Windowed"

[scrolling]
history = 10000

[font]
size = 12.0

[selection]
save_to_clipboard = true

[colors]
draw_bold_text_with_bright_colors = true

